version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: bot_db
    restart: always

    # Вместо ручного environment используем .env
    env_file:
      - .env
    
    # Если хотите явно прописать, что именно читается, можете:
    # environment:
    #   MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #   MARIADB_DATABASE: ${DB_NAME}
    #   MARIADB_USER: ${DB_USER}
    #   MARIADB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    container_name: django_web
    # мапим порт
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      - db

    # Тоже считываем .env
    env_file:
      - .env

    volumes:
      - .:/app

    command: ["python", "manage.py", "runbot"]

volumes:
  db_data:
