version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: bot_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: parliament_bot
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
    volumes:
      - db_data:/var/lib/mysql

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      - db
    environment:
      # Передаём переменные окружения (если нужно), чтобы в settings.py подставить
      DB_HOST: db
      DB_NAME: parliament_bot
      DB_USER: dbuser
      DB_PASSWORD: dbpassword

      # Токен бота, ID админа, и т.п.
      TELEGRAM_API_TOKEN: "ВАШ_ТОКЕН"  # В реале лучше в .env
      ADMIN_USER_ID: "123456789"

    # Если хотим отлаживаться (монтировать код)
    volumes:
      - .:/app

    # Бот не требует внешнего порта, так как общается с Telegram
    # Но если вам нужен Django-admin по адресу http://localhost:8000/admin,
    # смените команду на "runserver 0.0.0.0:8000".
    # Или оставим как есть — бот не слушает порт, всё работает через Telegram API.
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]  # Для веб-интерфейса
    command: ["python", "manage.py", "runbot"]

volumes:
  db_data:
