services:
  web:
    image: mp_bot_docker-web
    container_name: django_web  # Фиксированное имя
    ports:
      - "8000:8000"  # Хост:Контейнер
    env_file:
      - .env  # Секреты
    volumes:
      - .:/app

  frontend:
    image: mp_bot_docker-frontend
    container_name: vue_frontend_dev
    ports:
      - "5173:5173"  # Vite HMR порт
    env_file:
      - .env  # Общие переменные с backend
    depends_on:
      - web  # Ждёт запуска web-сервиса (но не проверяет его готовность)
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always