services:
  web:
    image: mp_bot_docker-web
    container_name: django_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  bot:
    image: mp_bot_docker-bot
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "manage.py", "runbot"]

  frontend:
    image: mp_bot_docker-frontend
    container_name: vue_frontend_dev
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - web
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always