services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Добавляем хост для подключения к БД
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Добавляем хост для подключения к БД
    command: ["python", "manage.py", "runbot"]