# Generated by Django 5.1.7 on 2025-04-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Фамилия')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_text', models.TextField(verbose_name='Текст обращения')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактная информация')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Прикрепленный файл')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='telegram_bot.commissioninfo', verbose_name='Комиссия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='telegram_bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=20, verbose_name='Статус')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.appeal', verbose_name='Обращение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_position', models.CharField(help_text='Желаемая должность администратора.', max_length=255, verbose_name='Должность')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Возможные статусы: В ожидании, Одобрено, Отклонено.', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Комментарий администратора при отклонении.', null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to='telegram_bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос администратору',
                'verbose_name_plural': 'Запросы администраторам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status'], name='telegram_bo_status_2801fc_idx'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['created_at'], name='telegram_bo_created_eedc43_idx'),
        ),
    ]
