# Generated by Django 5.1.7 on 2025-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Возможные статусы: В ожидании, Одобрено, Отклонено.', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=255, verbose_name='Статус'),
        ),
    ]
