# Generated by Django 5.1.7 on 2025-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20250215_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
