# Generated by Django 5.1.7 on 2025-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_alter_adminrequest_status_alter_appeal_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=1, help_text='Текст уведомления, который будет отправлен пользователю.', verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Возможные статусы: В ожидании, Одобрено, Отклонено.', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=50, verbose_name='Статус'),
        ),
    ]
