# Generated by Django 5.1.7 on 2025-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(default='Новое', max_length=255),
        ),
    ]
