# Generated by Django 5.1.7 on 2025-04-09 15:57

import telegram_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_remove_notification_status_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Возможные статусы: В ожидании, Одобрено, Отклонено.', max_length=50, validators=[telegram_bot.models.validate_admin_request_status], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('rejected', 'Отклонено')], default='new', help_text='Возможные статусы: Новое, Обработано, Отклонено.', max_length=50, validators=[telegram_bot.models.validate_appeal_status], verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='adminrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='valid_admin_request_status'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'processed', 'rejected'])), name='valid_appeal_status'),
        ),
    ]
