# Generated by Django 5.1.7 on 2025-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_adminrequest_status_alter_appeal_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminrequest',
            constraint=models.UniqueConstraint(fields=('user',), name='one_request_per_user_any_status'),
        ),
    ]
