# Generated by Django 5.1.7 on 2025-03-26 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_appeal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.appeal'),
        ),
    ]
