# Generated by Django 5.1.7 on 2025-04-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_adminrequest_one_request_per_user_any_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_bot.adminrequest', verbose_name='Запрос администратору'),
        ),
    ]
